FROM python:3.11-alpine
ENV PYTHONUNBUFFERED=1
RUN apk add --no-cache iptables iproute2
WORKDIR /app


COPY src/tokenring.py .

RUN chmod +x tokenring.py

ENTRYPOINT ["./tokenring.py"]

STOPSIGNAL SIGKILL
