FROM docker.io/library/debian:bookworm-slim
WORKDIR /test

# 1. Add backports for up-to-date network packages
RUN apt-get update && apt-get install -y ca-certificates && \
    echo "deb http://deb.debian.org/debian bookworm-backports main" >> /etc/apt/sources.list

# 2. Install curl, podman-remote, and sudo
RUN apt-get update && apt-get install -y \
    podman \
    curl \
    sudo \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

ENV CONTAINER_HOST=unix:///run/podman/podman.sock

# Copy the compiled C counter app into system PATH
COPY src/counter.py .

# Copy tests layout
COPY test/run_tests.sh run_tests
COPY test/ .

RUN chmod +x run_tests *.sh counter.py

ENTRYPOINT ["./run_tests"]

STOPSIGNAL SIGKILL