FROM python:3.11-alpine
ENV PYTHONUNBUFFERED=1
RUN apk add --no-cache iptables iproute2
WORKDIR /app


COPY src/workqueue.py .

RUN chmod +x workqueue.py

ENTRYPOINT ["./workqueue.py"]

STOPSIGNAL SIGKILL
