FROM python:3.11-alpine
ENV PYTHONUNBUFFERED=1
RUN apk add --no-cache iptables iproute2
WORKDIR /app

COPY config.py .
COPY mesh_proxy.py .
COPY snapshot_handler.py .
COPY entrypoint.sh .

RUN chmod +x entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

STOPSIGNAL SIGKILL